import { Category, Recipe, BlogPost } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Italian',
    description: 'Classic Italian cuisine from pasta to pizza',
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'italian'
  },
  {
    id: '2',
    name: 'Asian',
    description: 'Authentic flavors from across Asia',
    image_url: 'https://images.pexels.com/photos/1907244/pexels-photo-1907244.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'asian'
  },
  {
    id: '3',
    name: 'Desserts',
    description: 'Sweet treats and delightful desserts',
    image_url: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'desserts'
  },
  {
    id: '4',
    name: 'Mexican',
    description: 'Spicy and vibrant Mexican dishes',
    image_url: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'mexican'
  },
  {
    id: '5',
    name: 'Breakfast',
    description: 'Start your day with delicious breakfast recipes',
    image_url: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'breakfast'
  },
  {
    id: '6',
    name: 'Seafood',
    description: 'Fresh and flavorful seafood dishes',
    image_url: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'seafood'
  },
  {
    id: '7',
    name: 'Vegetarian',
    description: 'Healthy and delicious plant-based meals',
    image_url: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=800',
    slug: 'vegetarian'
  }
];

export const recipes: Recipe[] = [
  // Italian Recipes
  {
    id: 'i1',
    category_id: '1',
    title: 'Classic Spaghetti Carbonara',
    description: 'Creamy Roman pasta with pancetta and egg',
    image_url: 'https://images.pexels.com/photos/4518842/pexels-photo-4518842.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['400g spaghetti', '200g pancetta', '4 eggs', '100g Pecorino Romano', 'Black pepper', 'Salt'],
    instructions: ['Boil pasta in salted water', 'Fry pancetta until crispy', 'Beat eggs with cheese', 'Mix hot pasta with pancetta', 'Add egg mixture off heat', 'Serve with extra cheese'],
    slug: 'classic-spaghetti-carbonara'
  },
  {
    id: 'i2',
    category_id: '1',
    title: 'Margherita Pizza',
    description: 'Traditional Neapolitan pizza with fresh mozzarella',
    image_url: 'https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 90,
    cook_time: 12,
    servings: 2,
    difficulty: 'Medium',
    ingredients: ['Pizza dough', '200g San Marzano tomatoes', '250g fresh mozzarella', 'Fresh basil', 'Olive oil', 'Salt'],
    instructions: ['Stretch pizza dough', 'Spread tomato sauce', 'Add torn mozzarella', 'Drizzle olive oil', 'Bake at 500°F for 10-12 minutes', 'Top with fresh basil'],
    slug: 'margherita-pizza'
  },
  {
    id: 'i3',
    category_id: '1',
    title: 'Chicken Parmigiana',
    description: 'Breaded chicken with marinara and melted cheese',
    image_url: 'https://images.pexels.com/photos/8697626/pexels-photo-8697626.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 30,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['4 chicken breasts', 'Breadcrumbs', '2 eggs', 'Marinara sauce', 'Mozzarella cheese', 'Parmesan cheese'],
    instructions: ['Pound chicken thin', 'Bread with egg and breadcrumbs', 'Fry until golden', 'Top with sauce and cheese', 'Bake until cheese melts', 'Serve with pasta'],
    slug: 'chicken-parmigiana'
  },
  {
    id: 'i4',
    category_id: '1',
    title: 'Lasagna Bolognese',
    description: 'Layers of pasta, meat sauce, and béchamel',
    image_url: 'https://images.pexels.com/photos/4079520/pexels-photo-4079520.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 40,
    cook_time: 60,
    servings: 8,
    difficulty: 'Hard',
    ingredients: ['Lasagna sheets', '500g ground beef', 'Tomato sauce', 'Béchamel sauce', 'Parmesan', 'Mozzarella'],
    instructions: ['Make bolognese sauce', 'Prepare béchamel', 'Layer pasta, bolognese, béchamel', 'Repeat layers', 'Top with cheese', 'Bake at 375°F for 45 minutes'],
    slug: 'lasagna-bolognese'
  },
  {
    id: 'i5',
    category_id: '1',
    title: 'Risotto alla Milanese',
    description: 'Creamy saffron risotto from Milan',
    image_url: 'https://images.pexels.com/photos/8601366/pexels-photo-8601366.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 30,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Arborio rice', 'Saffron', 'White wine', 'Parmesan', 'Butter', 'Chicken stock'],
    instructions: ['Toast rice in butter', 'Add wine, let evaporate', 'Add stock gradually', 'Stir continuously', 'Add saffron', 'Finish with butter and parmesan'],
    slug: 'risotto-alla-milanese'
  },
  {
    id: 'i6',
    category_id: '1',
    title: 'Fettuccine Alfredo',
    description: 'Rich and creamy pasta with butter and parmesan',
    image_url: 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 5,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Fettuccine pasta', 'Heavy cream', 'Butter', 'Parmesan cheese', 'Garlic', 'Parsley'],
    instructions: ['Cook pasta al dente', 'Heat cream and butter', 'Add minced garlic', 'Toss pasta in sauce', 'Add parmesan', 'Garnish with parsley'],
    slug: 'fettuccine-alfredo'
  },
  {
    id: 'i7',
    category_id: '1',
    title: 'Osso Buco',
    description: 'Braised veal shanks in white wine',
    image_url: 'https://images.pexels.com/photos/9986228/pexels-photo-9986228.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 120,
    servings: 4,
    difficulty: 'Hard',
    ingredients: ['Veal shanks', 'White wine', 'Tomatoes', 'Carrots', 'Celery', 'Gremolata'],
    instructions: ['Brown veal shanks', 'Sauté vegetables', 'Add wine and tomatoes', 'Braise for 2 hours', 'Make gremolata', 'Serve with risotto'],
    slug: 'osso-buco'
  },
  {
    id: 'i8',
    category_id: '1',
    title: 'Caprese Salad',
    description: 'Fresh tomatoes, mozzarella, and basil',
    image_url: 'https://images.pexels.com/photos/1435903/pexels-photo-1435903.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 0,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Tomatoes', 'Fresh mozzarella', 'Fresh basil', 'Extra virgin olive oil', 'Balsamic glaze', 'Sea salt'],
    instructions: ['Slice tomatoes and mozzarella', 'Arrange alternating slices', 'Add basil leaves', 'Drizzle with olive oil', 'Add balsamic glaze', 'Season with salt'],
    slug: 'caprese-salad'
  },
  {
    id: 'i9',
    category_id: '1',
    title: 'Tiramisu',
    description: 'Classic Italian coffee-flavored dessert',
    image_url: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 0,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Ladyfingers', 'Mascarpone', 'Eggs', 'Espresso', 'Cocoa powder', 'Sugar'],
    instructions: ['Make mascarpone cream', 'Dip ladyfingers in espresso', 'Layer cookies and cream', 'Repeat layers', 'Refrigerate 4 hours', 'Dust with cocoa'],
    slug: 'tiramisu'
  },
  {
    id: 'i10',
    category_id: '1',
    title: 'Penne Arrabbiata',
    description: 'Spicy tomato pasta from Rome',
    image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Penne pasta', 'Tomatoes', 'Garlic', 'Red chili flakes', 'Olive oil', 'Parsley'],
    instructions: ['Cook pasta', 'Sauté garlic and chili', 'Add crushed tomatoes', 'Simmer sauce', 'Toss with pasta', 'Garnish with parsley'],
    slug: 'penne-arrabbiata'
  },

  // Asian Recipes
  {
    id: 'a1',
    category_id: '2',
    title: 'Pad Thai',
    description: 'Classic Thai stir-fried noodles',
    image_url: 'https://images.pexels.com/photos/4393426/pexels-photo-4393426.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Rice noodles', 'Shrimp', 'Eggs', 'Bean sprouts', 'Peanuts', 'Tamarind sauce'],
    instructions: ['Soak noodles', 'Stir-fry shrimp', 'Scramble eggs', 'Add noodles and sauce', 'Toss with vegetables', 'Top with peanuts'],
    slug: 'pad-thai'
  },
  {
    id: 'a2',
    category_id: '2',
    title: 'Chicken Teriyaki',
    description: 'Sweet and savory Japanese chicken',
    image_url: 'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Chicken thighs', 'Soy sauce', 'Mirin', 'Sugar', 'Ginger', 'Garlic'],
    instructions: ['Marinate chicken', 'Pan-fry chicken', 'Make teriyaki sauce', 'Glaze chicken', 'Reduce sauce', 'Serve with rice'],
    slug: 'chicken-teriyaki'
  },
  {
    id: 'a3',
    category_id: '2',
    title: 'Beef Pho',
    description: 'Vietnamese rice noodle soup',
    image_url: 'https://images.pexels.com/photos/1907244/pexels-photo-1907244.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 180,
    servings: 6,
    difficulty: 'Hard',
    ingredients: ['Beef bones', 'Rice noodles', 'Beef sirloin', 'Star anise', 'Cinnamon', 'Fresh herbs'],
    instructions: ['Roast bones', 'Simmer broth 3 hours', 'Strain and season', 'Cook noodles', 'Slice beef thin', 'Assemble bowls with toppings'],
    slug: 'beef-pho'
  },
  {
    id: 'a4',
    category_id: '2',
    title: 'Kung Pao Chicken',
    description: 'Spicy Szechuan chicken with peanuts',
    image_url: 'https://images.pexels.com/photos/2456435/pexels-photo-2456435.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Chicken breast', 'Peanuts', 'Dried chilies', 'Szechuan peppercorns', 'Soy sauce', 'Rice vinegar'],
    instructions: ['Marinate chicken', 'Stir-fry chilies', 'Add chicken', 'Make sauce', 'Add peanuts', 'Serve over rice'],
    slug: 'kung-pao-chicken'
  },
  {
    id: 'a5',
    category_id: '2',
    title: 'Sushi Rolls',
    description: 'Fresh California rolls with crab and avocado',
    image_url: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 40,
    cook_time: 20,
    servings: 4,
    difficulty: 'Hard',
    ingredients: ['Sushi rice', 'Nori sheets', 'Crab meat', 'Avocado', 'Cucumber', 'Rice vinegar'],
    instructions: ['Cook and season rice', 'Place nori on mat', 'Spread rice', 'Add fillings', 'Roll tightly', 'Slice and serve'],
    slug: 'sushi-rolls'
  },
  {
    id: 'a6',
    category_id: '2',
    title: 'Korean Bibimbap',
    description: 'Mixed rice bowl with vegetables and egg',
    image_url: 'https://images.pexels.com/photos/1907244/pexels-photo-1907244.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 20,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Rice', 'Beef', 'Spinach', 'Carrots', 'Eggs', 'Gochujang sauce'],
    instructions: ['Cook rice', 'Marinate and cook beef', 'Sauté vegetables separately', 'Fry eggs', 'Arrange in bowl', 'Serve with gochujang'],
    slug: 'korean-bibimbap'
  },
  {
    id: 'a7',
    category_id: '2',
    title: 'Tom Yum Soup',
    description: 'Spicy and sour Thai shrimp soup',
    image_url: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 20,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Shrimp', 'Lemongrass', 'Galangal', 'Lime leaves', 'Thai chilies', 'Fish sauce'],
    instructions: ['Boil aromatics in stock', 'Add shrimp', 'Season with fish sauce', 'Add lime juice', 'Add chilies', 'Garnish with cilantro'],
    slug: 'tom-yum-soup'
  },
  {
    id: 'a8',
    category_id: '2',
    title: 'Chicken Fried Rice',
    description: 'Chinese-style fried rice with vegetables',
    image_url: 'https://images.pexels.com/photos/2456435/pexels-photo-2456435.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Day-old rice', 'Chicken', 'Eggs', 'Peas', 'Carrots', 'Soy sauce'],
    instructions: ['Scramble eggs', 'Stir-fry chicken', 'Add vegetables', 'Add rice', 'Season with soy sauce', 'Toss everything together'],
    slug: 'chicken-fried-rice'
  },
  {
    id: 'a9',
    category_id: '2',
    title: 'Ramen Bowl',
    description: 'Japanese noodle soup with pork and egg',
    image_url: 'https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 120,
    servings: 4,
    difficulty: 'Hard',
    ingredients: ['Ramen noodles', 'Pork belly', 'Eggs', 'Chicken broth', 'Miso paste', 'Green onions'],
    instructions: ['Make rich broth', 'Braise pork belly', 'Marinate soft-boiled eggs', 'Cook noodles', 'Assemble bowls', 'Add toppings'],
    slug: 'ramen-bowl'
  },
  {
    id: 'a10',
    category_id: '2',
    title: 'Spring Rolls',
    description: 'Fresh Vietnamese rice paper rolls',
    image_url: 'https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 0,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Rice paper', 'Shrimp', 'Rice noodles', 'Lettuce', 'Mint', 'Peanut sauce'],
    instructions: ['Soften rice paper', 'Add lettuce', 'Place noodles and shrimp', 'Add herbs', 'Roll tightly', 'Serve with peanut sauce'],
    slug: 'spring-rolls'
  },

  // Desserts
  {
    id: 'd1',
    category_id: '3',
    title: 'Chocolate Lava Cake',
    description: 'Molten chocolate center dessert',
    image_url: 'https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 12,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Dark chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla'],
    instructions: ['Melt chocolate and butter', 'Beat eggs and sugar', 'Combine mixtures', 'Add flour', 'Pour into ramekins', 'Bake at 425°F for 12 minutes'],
    slug: 'chocolate-lava-cake'
  },
  {
    id: 'd2',
    category_id: '3',
    title: 'Crème Brûlée',
    description: 'French custard with caramelized sugar top',
    image_url: 'https://images.pexels.com/photos/3026808/pexels-photo-3026808.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 45,
    servings: 6,
    difficulty: 'Hard',
    ingredients: ['Heavy cream', 'Egg yolks', 'Sugar', 'Vanilla bean', 'Extra sugar for topping'],
    instructions: ['Heat cream with vanilla', 'Whisk yolks and sugar', 'Combine and strain', 'Pour into ramekins', 'Bake in water bath', 'Torch sugar topping'],
    slug: 'creme-brulee'
  },
  {
    id: 'd3',
    category_id: '3',
    title: 'New York Cheesecake',
    description: 'Rich and creamy classic cheesecake',
    image_url: 'https://images.pexels.com/photos/3938023/pexels-photo-3938023.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 60,
    servings: 12,
    difficulty: 'Medium',
    ingredients: ['Cream cheese', 'Graham crackers', 'Sugar', 'Eggs', 'Sour cream', 'Vanilla'],
    instructions: ['Make graham crust', 'Beat cream cheese and sugar', 'Add eggs one at a time', 'Pour into pan', 'Bake in water bath', 'Chill overnight'],
    slug: 'new-york-cheesecake'
  },
  {
    id: 'd4',
    category_id: '3',
    title: 'Macarons',
    description: 'Delicate French almond cookies',
    image_url: 'https://images.pexels.com/photos/3776942/pexels-photo-3776942.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 60,
    cook_time: 15,
    servings: 24,
    difficulty: 'Hard',
    ingredients: ['Almond flour', 'Powdered sugar', 'Egg whites', 'Granulated sugar', 'Food coloring', 'Buttercream'],
    instructions: ['Make meringue', 'Fold in dry ingredients', 'Pipe circles', 'Let rest 30 minutes', 'Bake at 300°F', 'Fill with buttercream'],
    slug: 'macarons'
  },
  {
    id: 'd5',
    category_id: '3',
    title: 'Apple Pie',
    description: 'Classic American apple pie',
    image_url: 'https://images.pexels.com/photos/5945786/pexels-photo-5945786.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 50,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Pie crust', 'Apples', 'Sugar', 'Cinnamon', 'Butter', 'Lemon juice'],
    instructions: ['Roll out bottom crust', 'Mix apple filling', 'Fill pie shell', 'Top with lattice crust', 'Brush with egg wash', 'Bake until golden'],
    slug: 'apple-pie'
  },
  {
    id: 'd6',
    category_id: '3',
    title: 'Panna Cotta',
    description: 'Italian cream dessert with berry sauce',
    image_url: 'https://images.pexels.com/photos/1120970/pexels-photo-1120970.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 5,
    servings: 6,
    difficulty: 'Easy',
    ingredients: ['Heavy cream', 'Gelatin', 'Sugar', 'Vanilla', 'Berries', 'Honey'],
    instructions: ['Bloom gelatin', 'Heat cream and sugar', 'Dissolve gelatin', 'Pour into molds', 'Refrigerate 4 hours', 'Serve with berry sauce'],
    slug: 'panna-cotta'
  },
  {
    id: 'd7',
    category_id: '3',
    title: 'Brownies',
    description: 'Fudgy chocolate brownies',
    image_url: 'https://images.pexels.com/photos/3776942/pexels-photo-3776942.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 25,
    servings: 16,
    difficulty: 'Easy',
    ingredients: ['Chocolate', 'Butter', 'Sugar', 'Eggs', 'Flour', 'Cocoa powder'],
    instructions: ['Melt chocolate and butter', 'Beat eggs and sugar', 'Combine mixtures', 'Add flour', 'Pour into pan', 'Bake at 350°F'],
    slug: 'brownies'
  },
  {
    id: 'd8',
    category_id: '3',
    title: 'Lemon Tart',
    description: 'Tangy lemon custard in pastry shell',
    image_url: 'https://images.pexels.com/photos/7525127/pexels-photo-7525127.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 40,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Tart shell', 'Lemons', 'Eggs', 'Sugar', 'Butter', 'Cream'],
    instructions: ['Blind bake tart shell', 'Make lemon curd', 'Pour into shell', 'Bake until set', 'Cool completely', 'Dust with powdered sugar'],
    slug: 'lemon-tart'
  },
  {
    id: 'd9',
    category_id: '3',
    title: 'Chocolate Mousse',
    description: 'Light and airy chocolate dessert',
    image_url: 'https://images.pexels.com/photos/132694/pexels-photo-132694.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 0,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Dark chocolate', 'Heavy cream', 'Eggs', 'Sugar', 'Vanilla', 'Salt'],
    instructions: ['Melt chocolate', 'Whip cream', 'Beat egg whites', 'Fold chocolate into cream', 'Fold in egg whites', 'Chill 4 hours'],
    slug: 'chocolate-mousse'
  },
  {
    id: 'd10',
    category_id: '3',
    title: 'Carrot Cake',
    description: 'Moist spiced cake with cream cheese frosting',
    image_url: 'https://images.pexels.com/photos/4099235/pexels-photo-4099235.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 25,
    cook_time: 35,
    servings: 12,
    difficulty: 'Medium',
    ingredients: ['Carrots', 'Flour', 'Sugar', 'Eggs', 'Oil', 'Cream cheese frosting'],
    instructions: ['Mix dry ingredients', 'Combine wet ingredients', 'Fold in grated carrots', 'Pour into pans', 'Bake at 350°F', 'Frost when cool'],
    slug: 'carrot-cake'
  },

  // Mexican
  {
    id: 'm1',
    category_id: '4',
    title: 'Tacos al Pastor',
    description: 'Marinated pork tacos with pineapple',
    image_url: 'https://images.pexels.com/photos/7613568/pexels-photo-7613568.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 120,
    cook_time: 15,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Pork shoulder', 'Pineapple', 'Achiote paste', 'Corn tortillas', 'Onion', 'Cilantro'],
    instructions: ['Marinate pork overnight', 'Grill or pan-fry pork', 'Char pineapple', 'Warm tortillas', 'Assemble tacos', 'Top with onion and cilantro'],
    slug: 'tacos-al-pastor'
  },
  {
    id: 'm2',
    category_id: '4',
    title: 'Chicken Enchiladas',
    description: 'Rolled tortillas with chicken and sauce',
    image_url: 'https://images.pexels.com/photos/5737241/pexels-photo-5737241.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 25,
    servings: 6,
    difficulty: 'Easy',
    ingredients: ['Chicken', 'Tortillas', 'Enchilada sauce', 'Cheese', 'Onion', 'Sour cream'],
    instructions: ['Shred cooked chicken', 'Warm tortillas', 'Fill with chicken and cheese', 'Roll and place in pan', 'Cover with sauce', 'Bake at 375°F'],
    slug: 'chicken-enchiladas'
  },
  {
    id: 'm3',
    category_id: '4',
    title: 'Guacamole',
    description: 'Fresh avocado dip',
    image_url: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 0,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Avocados', 'Lime', 'Tomatoes', 'Onion', 'Jalapeño', 'Cilantro'],
    instructions: ['Mash avocados', 'Add lime juice', 'Dice tomatoes and onion', 'Mince jalapeño', 'Mix everything', 'Season with salt'],
    slug: 'guacamole'
  },
  {
    id: 'm4',
    category_id: '4',
    title: 'Chile Rellenos',
    description: 'Stuffed poblano peppers',
    image_url: 'https://images.pexels.com/photos/6646297/pexels-photo-6646297.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 30,
    servings: 4,
    difficulty: 'Hard',
    ingredients: ['Poblano peppers', 'Cheese', 'Eggs', 'Flour', 'Tomato sauce', 'Spices'],
    instructions: ['Roast and peel peppers', 'Stuff with cheese', 'Coat in egg batter', 'Fry until golden', 'Serve with sauce', 'Garnish with crema'],
    slug: 'chile-rellenos'
  },
  {
    id: 'm5',
    category_id: '4',
    title: 'Carnitas',
    description: 'Slow-cooked Mexican pulled pork',
    image_url: 'https://images.pexels.com/photos/8448323/pexels-photo-8448323.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 180,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Pork shoulder', 'Orange juice', 'Lime', 'Cumin', 'Bay leaves', 'Garlic'],
    instructions: ['Season pork', 'Braise in oven 3 hours', 'Shred meat', 'Crisp under broiler', 'Serve in tacos', 'Top with salsa'],
    slug: 'carnitas'
  },
  {
    id: 'm6',
    category_id: '4',
    title: 'Quesadillas',
    description: 'Grilled cheese-filled tortillas',
    image_url: 'https://images.pexels.com/photos/5737241/pexels-photo-5737241.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Flour tortillas', 'Cheese', 'Chicken or beef', 'Peppers', 'Onions', 'Salsa'],
    instructions: ['Add cheese to tortilla', 'Add fillings', 'Fold in half', 'Grill until golden', 'Flip and cook other side', 'Cut and serve'],
    slug: 'quesadillas'
  },
  {
    id: 'm7',
    category_id: '4',
    title: 'Pozole',
    description: 'Mexican hominy soup',
    image_url: 'https://images.pexels.com/photos/6646297/pexels-photo-6646297.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 120,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Pork shoulder', 'Hominy', 'Dried chilies', 'Garlic', 'Onion', 'Toppings'],
    instructions: ['Cook pork in broth', 'Add hominy', 'Make chili sauce', 'Combine and simmer', 'Shred pork', 'Serve with toppings'],
    slug: 'pozole'
  },
  {
    id: 'm8',
    category_id: '4',
    title: 'Elote',
    description: 'Mexican street corn',
    image_url: 'https://images.pexels.com/photos/5737241/pexels-photo-5737241.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Corn on cob', 'Mayo', 'Cotija cheese', 'Chili powder', 'Lime', 'Cilantro'],
    instructions: ['Grill corn', 'Brush with mayo', 'Sprinkle cheese', 'Add chili powder', 'Squeeze lime', 'Garnish with cilantro'],
    slug: 'elote'
  },
  {
    id: 'm9',
    category_id: '4',
    title: 'Mole Poblano',
    description: 'Rich chocolate chili sauce with chicken',
    image_url: 'https://images.pexels.com/photos/8448323/pexels-photo-8448323.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 45,
    cook_time: 90,
    servings: 6,
    difficulty: 'Hard',
    ingredients: ['Chicken', 'Dried chilies', 'Chocolate', 'Nuts', 'Spices', 'Sesame seeds'],
    instructions: ['Toast and soak chilies', 'Blend with chocolate and spices', 'Simmer sauce', 'Cook chicken', 'Cover with mole', 'Garnish with sesame'],
    slug: 'mole-poblano'
  },
  {
    id: 'm10',
    category_id: '4',
    title: 'Churros',
    description: 'Fried dough with cinnamon sugar',
    image_url: 'https://images.pexels.com/photos/3776942/pexels-photo-3776942.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 15,
    servings: 8,
    difficulty: 'Medium',
    ingredients: ['Flour', 'Water', 'Butter', 'Sugar', 'Cinnamon', 'Chocolate sauce'],
    instructions: ['Make dough', 'Pipe into oil', 'Fry until golden', 'Roll in cinnamon sugar', 'Make chocolate sauce', 'Serve hot'],
    slug: 'churros'
  },

  // Breakfast
  {
    id: 'b1',
    category_id: '5',
    title: 'Fluffy Pancakes',
    description: 'Light and airy buttermilk pancakes',
    image_url: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Flour', 'Buttermilk', 'Eggs', 'Baking powder', 'Sugar', 'Butter'],
    instructions: ['Mix dry ingredients', 'Combine wet ingredients', 'Fold together gently', 'Heat griddle', 'Pour batter', 'Flip when bubbles form'],
    slug: 'fluffy-pancakes'
  },
  {
    id: 'b2',
    category_id: '5',
    title: 'Eggs Benedict',
    description: 'Poached eggs with hollandaise on English muffins',
    image_url: 'https://images.pexels.com/photos/2374946/pexels-photo-2374946.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 20,
    servings: 2,
    difficulty: 'Hard',
    ingredients: ['English muffins', 'Eggs', 'Canadian bacon', 'Butter', 'Lemon juice', 'Cayenne'],
    instructions: ['Make hollandaise sauce', 'Toast muffins', 'Cook bacon', 'Poach eggs', 'Assemble', 'Top with hollandaise'],
    slug: 'eggs-benedict'
  },
  {
    id: 'b3',
    category_id: '5',
    title: 'French Toast',
    description: 'Cinnamon-spiced eggy bread',
    image_url: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Bread', 'Eggs', 'Milk', 'Cinnamon', 'Vanilla', 'Maple syrup'],
    instructions: ['Whisk eggs, milk, cinnamon', 'Dip bread slices', 'Cook in butter', 'Flip when golden', 'Serve with syrup', 'Top with berries'],
    slug: 'french-toast'
  },
  {
    id: 'b4',
    category_id: '5',
    title: 'Breakfast Burrito',
    description: 'Scrambled eggs, cheese, and bacon wrapped',
    image_url: 'https://images.pexels.com/photos/7194915/pexels-photo-7194915.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Tortillas', 'Eggs', 'Bacon', 'Cheese', 'Potatoes', 'Salsa'],
    instructions: ['Cook bacon', 'Scramble eggs', 'Cook hash browns', 'Warm tortillas', 'Fill with ingredients', 'Roll and serve'],
    slug: 'breakfast-burrito'
  },
  {
    id: 'b5',
    category_id: '5',
    title: 'Avocado Toast',
    description: 'Mashed avocado on crispy sourdough',
    image_url: 'https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 5,
    cook_time: 5,
    servings: 2,
    difficulty: 'Easy',
    ingredients: ['Sourdough bread', 'Avocado', 'Lime', 'Red pepper flakes', 'Eggs', 'Salt'],
    instructions: ['Toast bread', 'Mash avocado', 'Add lime and salt', 'Spread on toast', 'Top with fried egg', 'Sprinkle pepper flakes'],
    slug: 'avocado-toast'
  },
  {
    id: 'b6',
    category_id: '5',
    title: 'Belgian Waffles',
    description: 'Crispy outside, fluffy inside waffles',
    image_url: 'https://images.pexels.com/photos/4825701/pexels-photo-4825701.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 20,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Flour', 'Eggs', 'Milk', 'Butter', 'Sugar', 'Vanilla'],
    instructions: ['Mix dry ingredients', 'Combine wet ingredients', 'Fold together', 'Pour into waffle iron', 'Cook until golden', 'Serve with toppings'],
    slug: 'belgian-waffles'
  },
  {
    id: 'b7',
    category_id: '5',
    title: 'Shakshuka',
    description: 'Eggs poached in spicy tomato sauce',
    image_url: 'https://images.pexels.com/photos/2067396/pexels-photo-2067396.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 25,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Tomatoes', 'Eggs', 'Peppers', 'Onion', 'Cumin', 'Feta cheese'],
    instructions: ['Sauté peppers and onion', 'Add tomatoes and spices', 'Simmer sauce', 'Create wells', 'Crack eggs into wells', 'Cook until set'],
    slug: 'shakshuka'
  },
  {
    id: 'b8',
    category_id: '5',
    title: 'Granola Bowl',
    description: 'Homemade granola with yogurt and berries',
    image_url: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 25,
    servings: 6,
    difficulty: 'Easy',
    ingredients: ['Oats', 'Honey', 'Nuts', 'Greek yogurt', 'Berries', 'Coconut'],
    instructions: ['Mix oats, honey, nuts', 'Bake until golden', 'Let cool', 'Combine yogurt and berries', 'Top with granola', 'Add fresh fruit'],
    slug: 'granola-bowl'
  },
  {
    id: 'b9',
    category_id: '5',
    title: 'Breakfast Sandwich',
    description: 'Egg, cheese, and bacon on English muffin',
    image_url: 'https://images.pexels.com/photos/7194915/pexels-photo-7194915.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 5,
    cook_time: 10,
    servings: 1,
    difficulty: 'Easy',
    ingredients: ['English muffin', 'Egg', 'Bacon', 'Cheese', 'Butter', 'Salt'],
    instructions: ['Cook bacon', 'Fry egg', 'Toast muffin', 'Add cheese to egg', 'Assemble sandwich', 'Serve hot'],
    slug: 'breakfast-sandwich'
  },
  {
    id: 'b10',
    category_id: '5',
    title: 'Smoothie Bowl',
    description: 'Thick smoothie topped with fruits and granola',
    image_url: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 0,
    servings: 2,
    difficulty: 'Easy',
    ingredients: ['Frozen berries', 'Banana', 'Greek yogurt', 'Granola', 'Honey', 'Fresh fruit'],
    instructions: ['Blend frozen fruit', 'Add yogurt', 'Pour into bowl', 'Arrange toppings', 'Drizzle honey', 'Serve immediately'],
    slug: 'smoothie-bowl'
  },

  // Seafood
  {
    id: 's1',
    category_id: '6',
    title: 'Grilled Salmon',
    description: 'Perfect grilled salmon with lemon butter',
    image_url: 'https://images.pexels.com/photos/3296682/pexels-photo-3296682.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Salmon fillets', 'Lemon', 'Butter', 'Garlic', 'Dill', 'Salt'],
    instructions: ['Season salmon', 'Preheat grill', 'Grill skin-side down', 'Flip carefully', 'Make lemon butter sauce', 'Serve with sauce'],
    slug: 'grilled-salmon'
  },
  {
    id: 's2',
    category_id: '6',
    title: 'Shrimp Scampi',
    description: 'Garlic butter shrimp with white wine',
    image_url: 'https://images.pexels.com/photos/725997/pexels-photo-725997.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Shrimp', 'Garlic', 'White wine', 'Butter', 'Lemon', 'Parsley'],
    instructions: ['Sauté garlic in butter', 'Add shrimp', 'Pour in wine', 'Cook until pink', 'Add lemon juice', 'Garnish with parsley'],
    slug: 'shrimp-scampi'
  },
  {
    id: 's3',
    category_id: '6',
    title: 'Fish Tacos',
    description: 'Crispy fish with cabbage slaw',
    image_url: 'https://images.pexels.com/photos/4958792/pexels-photo-4958792.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 15,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['White fish', 'Tortillas', 'Cabbage', 'Lime', 'Chipotle mayo', 'Cilantro'],
    instructions: ['Season and fry fish', 'Make cabbage slaw', 'Warm tortillas', 'Break fish into pieces', 'Assemble tacos', 'Top with sauce'],
    slug: 'fish-tacos'
  },
  {
    id: 's4',
    category_id: '6',
    title: 'Lobster Roll',
    description: 'Maine-style lobster salad sandwich',
    image_url: 'https://images.pexels.com/photos/6419120/pexels-photo-6419120.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 10,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Lobster meat', 'Mayo', 'Celery', 'Lemon', 'Hot dog buns', 'Butter'],
    instructions: ['Chop lobster meat', 'Mix with mayo and celery', 'Season with lemon', 'Toast buttered buns', 'Fill with lobster salad', 'Serve chilled'],
    slug: 'lobster-roll'
  },
  {
    id: 's5',
    category_id: '6',
    title: 'Paella',
    description: 'Spanish rice with seafood and saffron',
    image_url: 'https://images.pexels.com/photos/16743486/pexels-photo-16743486.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 40,
    servings: 6,
    difficulty: 'Hard',
    ingredients: ['Rice', 'Shrimp', 'Mussels', 'Clams', 'Saffron', 'Peppers'],
    instructions: ['Sauté vegetables', 'Add rice and saffron', 'Pour in stock', 'Arrange seafood on top', 'Cook without stirring', 'Let rest before serving'],
    slug: 'paella'
  },
  {
    id: 's6',
    category_id: '6',
    title: 'Crab Cakes',
    description: 'Pan-fried Maryland crab cakes',
    image_url: 'https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 10,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Crab meat', 'Breadcrumbs', 'Mayo', 'Egg', 'Old Bay seasoning', 'Lemon'],
    instructions: ['Mix crab with binding', 'Form into cakes', 'Chill 30 minutes', 'Pan-fry until golden', 'Flip carefully', 'Serve with remoulade'],
    slug: 'crab-cakes'
  },
  {
    id: 's7',
    category_id: '6',
    title: 'Tuna Poke Bowl',
    description: 'Hawaiian-style raw tuna with rice',
    image_url: 'https://images.pexels.com/photos/2456435/pexels-photo-2456435.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Sushi-grade tuna', 'Soy sauce', 'Sesame oil', 'Rice', 'Avocado', 'Edamame'],
    instructions: ['Cube tuna', 'Marinate in soy and sesame', 'Cook sushi rice', 'Arrange rice in bowls', 'Top with tuna and vegetables', 'Garnish with sesame seeds'],
    slug: 'tuna-poke-bowl'
  },
  {
    id: 's8',
    category_id: '6',
    title: 'Clam Chowder',
    description: 'Creamy New England clam soup',
    image_url: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 30,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Clams', 'Potatoes', 'Onion', 'Bacon', 'Cream', 'Thyme'],
    instructions: ['Cook bacon', 'Sauté onions', 'Add potatoes and clam juice', 'Simmer until tender', 'Add clams and cream', 'Season and serve'],
    slug: 'clam-chowder'
  },
  {
    id: 's9',
    category_id: '6',
    title: 'Blackened Mahi Mahi',
    description: 'Cajun-spiced grilled fish',
    image_url: 'https://images.pexels.com/photos/3296682/pexels-photo-3296682.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Mahi mahi', 'Cajun seasoning', 'Butter', 'Lemon', 'Paprika', 'Garlic powder'],
    instructions: ['Coat fish in seasoning', 'Heat cast iron very hot', 'Add butter', 'Cook fish 3 minutes per side', 'Let rest', 'Serve with lemon'],
    slug: 'blackened-mahi-mahi'
  },
  {
    id: 's10',
    category_id: '6',
    title: 'Seafood Pasta',
    description: 'Mixed seafood in white wine sauce',
    image_url: 'https://images.pexels.com/photos/4518842/pexels-photo-4518842.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 20,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Linguine', 'Shrimp', 'Scallops', 'Mussels', 'White wine', 'Garlic'],
    instructions: ['Cook pasta', 'Sauté garlic', 'Add seafood', 'Pour in wine', 'Toss with pasta', 'Garnish with parsley'],
    slug: 'seafood-pasta'
  },

  // Vegetarian
  {
    id: 'v1',
    category_id: '7',
    title: 'Vegetable Stir Fry',
    description: 'Colorful mixed vegetables in savory sauce',
    image_url: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 10,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Mixed vegetables', 'Soy sauce', 'Ginger', 'Garlic', 'Sesame oil', 'Rice'],
    instructions: ['Heat wok', 'Stir-fry vegetables', 'Add aromatics', 'Pour in sauce', 'Toss to coat', 'Serve over rice'],
    slug: 'vegetable-stir-fry'
  },
  {
    id: 'v2',
    category_id: '7',
    title: 'Mushroom Risotto',
    description: 'Creamy rice with wild mushrooms',
    image_url: 'https://images.pexels.com/photos/8601366/pexels-photo-8601366.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 35,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Arborio rice', 'Mixed mushrooms', 'White wine', 'Parmesan', 'Butter', 'Vegetable stock'],
    instructions: ['Sauté mushrooms', 'Toast rice', 'Add wine', 'Gradually add stock', 'Stir constantly', 'Finish with butter and cheese'],
    slug: 'mushroom-risotto'
  },
  {
    id: 'v3',
    category_id: '7',
    title: 'Falafel',
    description: 'Crispy chickpea fritters',
    image_url: 'https://images.pexels.com/photos/6107787/pexels-photo-6107787.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 120,
    cook_time: 15,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Chickpeas', 'Herbs', 'Garlic', 'Cumin', 'Tahini', 'Lemon'],
    instructions: ['Soak chickpeas overnight', 'Blend with herbs and spices', 'Form into balls', 'Deep fry until golden', 'Drain on paper towels', 'Serve with tahini sauce'],
    slug: 'falafel'
  },
  {
    id: 'v4',
    category_id: '7',
    title: 'Eggplant Parmesan',
    description: 'Breaded eggplant with marinara and cheese',
    image_url: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 30,
    cook_time: 40,
    servings: 6,
    difficulty: 'Medium',
    ingredients: ['Eggplant', 'Breadcrumbs', 'Marinara sauce', 'Mozzarella', 'Parmesan', 'Basil'],
    instructions: ['Slice and salt eggplant', 'Bread and fry slices', 'Layer with sauce and cheese', 'Repeat layers', 'Bake until bubbly', 'Garnish with basil'],
    slug: 'eggplant-parmesan'
  },
  {
    id: 'v5',
    category_id: '7',
    title: 'Black Bean Burgers',
    description: 'Hearty vegetarian burger patties',
    image_url: 'https://images.pexels.com/photos/1639562/pexels-photo-1639562.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Black beans', 'Breadcrumbs', 'Egg', 'Onion', 'Spices', 'Burger buns'],
    instructions: ['Mash beans', 'Mix with binders and spices', 'Form patties', 'Pan-fry or grill', 'Toast buns', 'Assemble with toppings'],
    slug: 'black-bean-burgers'
  },
  {
    id: 'v6',
    category_id: '7',
    title: 'Vegetable Curry',
    description: 'Spiced Indian vegetable stew',
    image_url: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 30,
    servings: 6,
    difficulty: 'Easy',
    ingredients: ['Mixed vegetables', 'Coconut milk', 'Curry powder', 'Ginger', 'Garlic', 'Tomatoes'],
    instructions: ['Sauté aromatics', 'Add spices', 'Add vegetables', 'Pour in coconut milk', 'Simmer until tender', 'Serve with rice or naan'],
    slug: 'vegetable-curry'
  },
  {
    id: 'v7',
    category_id: '7',
    title: 'Caprese Pasta',
    description: 'Fresh tomato, mozzarella, and basil pasta',
    image_url: 'https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 10,
    cook_time: 15,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Pasta', 'Cherry tomatoes', 'Fresh mozzarella', 'Basil', 'Garlic', 'Olive oil'],
    instructions: ['Cook pasta', 'Sauté garlic', 'Add tomatoes', 'Toss with pasta', 'Add mozzarella', 'Top with fresh basil'],
    slug: 'caprese-pasta'
  },
  {
    id: 'v8',
    category_id: '7',
    title: 'Stuffed Bell Peppers',
    description: 'Peppers filled with quinoa and vegetables',
    image_url: 'https://images.pexels.com/photos/4958792/pexels-photo-4958792.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 20,
    cook_time: 40,
    servings: 4,
    difficulty: 'Medium',
    ingredients: ['Bell peppers', 'Quinoa', 'Black beans', 'Corn', 'Cheese', 'Spices'],
    instructions: ['Cut tops off peppers', 'Cook quinoa mixture', 'Fill peppers', 'Top with cheese', 'Bake at 375°F', 'Serve hot'],
    slug: 'stuffed-bell-peppers'
  },
  {
    id: 'v9',
    category_id: '7',
    title: 'Greek Salad',
    description: 'Fresh Mediterranean vegetable salad',
    image_url: 'https://images.pexels.com/photos/1435903/pexels-photo-1435903.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 0,
    servings: 4,
    difficulty: 'Easy',
    ingredients: ['Cucumbers', 'Tomatoes', 'Feta cheese', 'Olives', 'Red onion', 'Olive oil'],
    instructions: ['Chop vegetables', 'Add olives and feta', 'Make dressing', 'Toss salad', 'Season with oregano', 'Serve immediately'],
    slug: 'greek-salad'
  },
  {
    id: 'v10',
    category_id: '7',
    title: 'Lentil Soup',
    description: 'Hearty and nutritious lentil stew',
    image_url: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=800',
    prep_time: 15,
    cook_time: 40,
    servings: 6,
    difficulty: 'Easy',
    ingredients: ['Lentils', 'Carrots', 'Celery', 'Onion', 'Vegetable broth', 'Cumin'],
    instructions: ['Sauté vegetables', 'Add lentils and broth', 'Season with spices', 'Simmer 30 minutes', 'Blend partially if desired', 'Serve with bread'],
    slug: 'lentil-soup'
  }
];

export const blogs: BlogPost[] = [
  {
    id: 'blog1',
    title: '10 Essential Kitchen Tools Every Home Cook Needs',
    excerpt: 'Discover the must-have kitchen tools that will transform your cooking experience and make meal preparation easier and more enjoyable.',
    image_url: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Sarah Mitchell',
    date: '2024-03-15',
    read_time: 5,
   content:'Cooking at home is both an art and a science, and having the right tools can make all the difference. Whether you’re preparing a simple breakfast or experimenting with a new recipe, the right kitchen equipment will make your tasks easier, more efficient, and more enjoyable. Many new cooks get overwhelmed by the wide range of gadgets available, but the truth is, you only need a few essentials to build a solid foundation in the kitchen.',
   content1:'The first must-have tool is a chef’s knife. A good-quality, sharp chef’s knife is the backbone of every kitchen. From chopping vegetables to slicing meat, this tool handles most of your cutting needs. Investing in a sturdy, comfortable knife saves time and effort while also ensuring safety—since a sharp knife is far less likely to slip than a dull one.',
   content2:'Next, you need a cutting board. A durable board protects your countertops and provides a safe surface for cutting. Wooden or bamboo cutting boards are excellent for vegetables and bread, while plastic boards are great for raw meat since they’re easier to sanitize. Having a couple of boards on hand ensures you avoid cross-contamination while preparing meals.',
   content3:'A reliable set of measuring cups and spoons is also essential. Cooking may allow for creativity, but baking requires precision, and having the right measurements makes all the difference. Even for savory dishes, measuring ingredients like spices, sauces, or grains helps maintain consistency in flavor and texture, especially when following recipes.',
   content4:'Every home cook should also own a cast iron or non-stick skillet. A quality skillet is versatile enough for frying eggs, searing meat, or sautéing vegetables. Cast iron skillets are particularly durable and retain heat well, making them great for one-pan meals. On the other hand, non-stick skillets are ideal for delicate items like pancakes or fish, requiring less oil for cooking.',
   content5:'Another essential is a saucepan and a stockpot. These pans are the workhorses of any kitchen, perfect for boiling pasta, simmering sauces, or preparing soups and stews. A medium-sized saucepan is useful for daily cooking, while a larger stockpot comes in handy for family meals or batch cooking, especially if you enjoy meal prepping.',
   content6:'Don’t forget a mixing bowl set. Mixing bowls are incredibly versatile—they’re not only for mixing batters but also for marinating meat, tossing salads, or serving snacks. Opt for a set of bowls in different sizes, preferably stainless steel or glass, so you’re prepared for tasks both big and small.',
   content7:'Finally, no kitchen is complete without a wooden spoon and a spatula. These basic tools are surprisingly versatile and durable. Wooden spoons don’t scratch cookware and are heat resistant, while spatulas are perfect for scraping every bit of sauce or flipping food evenly. They may be small, but they play a big role in ensuring your meals turn out just right.',
    slug: 'essential-kitchen-tools'
  },
  {
    id: 'blog2',
    title: 'The Art of Meal Prepping: A Complete Guide',
    excerpt: 'Learn how to efficiently meal prep for the week ahead, saving time and money while enjoying delicious homemade meals every day.',
    image_url: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'James Chen',
    content:'Meal prepping has become more than just a food trend—it’s a lifestyle choice that helps people save time, eat healthier, and reduce stress during the week. At its core, meal prepping is about planning, preparing, and portioning your meals ahead of time so you always have nourishing options ready to go. Instead of scrambling every day to decide what to eat, you set aside a block of time—usually on the weekend—to prepare meals that will keep you fueled throughout the week.',
    content1:'One of the biggest benefits of meal prepping is the time you save. Imagine coming home after a long day and having dinner already cooked, or grabbing a ready-made lunch before heading to work. This not only reduces the temptation to order takeout but also ensures you’re making healthier choices. By cooking in bulk, you spend less time in the kitchen each day and more time enjoying your food and your life.',
    content2:'One of the biggest benefits of meal prepping is the time you save. Imagine coming home after a long day and having dinner already cooked, or grabbing a ready-made lunch before heading to work. This not only reduces the temptation to order takeout but also ensures you’re making healthier choices. By cooking in bulk, you spend less time in the kitchen each day and more time enjoying your food and your life.',
    content3:'Meal prepping also supports better nutrition. When you prepare your meals in advance, you’re in full control of the ingredients. You can focus on balanced portions of protein, carbohydrates, and healthy fats while cutting down on processed foods and unnecessary sugars. Having meals ready reduces the chances of reaching for unhealthy snacks when hunger strikes. It’s also a smart way to manage portion sizes, which can help with weight goals and overall health.',
    content4:'The key to successful meal prepping is planning. Start by choosing a few recipes you enjoy that share similar ingredients—this saves money and reduces food waste. For example, roasted chicken can be used in salads, wraps, or grain bowls, while cooked quinoa can be a base for multiple dishes. Once your menu is set, make a detailed grocery list to ensure you have everything you need.',
    content5:'When it comes to prepping, storage is just as important as cooking. Invest in good-quality containers that are freezer-safe, microwave-friendly, and easy to stack in your fridge. Labeling meals with the date can help you keep track of freshness and avoid waste. Some people like to prep full meals, while others prepare ingredients—such as chopping vegetables, marinating proteins, or cooking grains—so they can quickly assemble dishes during the week.',
    content6:'Meal prepping doesn’t have to mean eating the same thing every day. Variety keeps it exciting. Rotate proteins, change up your sauces, or add seasonal vegetables to keep your meals fresh and enjoyable. A little creativity ensures you never get bored, even if you’re eating from your meal prep containers most days.',
    content7:'Ultimately, meal prepping is about making your life easier and your diet more consistent. It’s a practical strategy for busy professionals, families, or anyone who wants to take control of their eating habits. With some planning, organization, and a few hours of effort, you’ll always have healthy, delicious meals at your fingertips.',
    date: '2024-03-10',
    read_time: 8,
    slug: 'meal-prepping-guide'
  },
  {
    id: 'blog3',
    title: 'Mastering the Perfect Pasta: Tips from Italian Chefs',
    excerpt: 'Unlock the secrets to cooking pasta like a true Italian with these professional tips and techniques that will elevate your dishes.',
    image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Marco Rossi',
    date: '2024-03-05',
    content:'Pasta is more than just a staple food in Italy—it’s a cultural symbol, a comfort dish, and an art form that Italians take seriously. While pasta is enjoyed worldwide, the way it’s prepared in Italy has a unique balance of tradition and simplicity. Italian chefs believe that making pasta the right way transforms a basic meal into a culinary experience. Mastering the perfect pasta doesn’t require professional training; it requires paying attention to details that chefs in Italy have passed down for generations.',
   content1:'The first step to perfect pasta is choosing the right pasta shape for the sauce. Italian chefs stress that the type of pasta you use matters as much as the sauce itself. For example, spaghetti pairs beautifully with light tomato or olive-oil-based sauces, while rigatoni and penne hold up better with thicker, creamier sauces. The grooves and shapes of the pasta are designed to capture the sauce, ensuring every bite is flavorful.',
   content2:'Next comes the importance of proper boiling technique. Italians always use a large pot with plenty of water—at least four to six liters per pound of pasta. Adding a generous handful of salt is non-negotiable because pasta must be seasoned while it cooks. Chefs say the water should taste “like the sea.” This ensures that the pasta itself carries flavor instead of relying entirely on the sauce.',
   content3:'Timing is another critical factor. Pasta should always be cooked al dente, meaning “to the tooth.” Italian chefs insist that pasta should be firm when bitten, not mushy. Overcooked pasta loses its structure and doesn’t absorb sauce properly. To achieve al dente, follow the cooking time on the package but taste the pasta a minute or two before it’s done. This small adjustment makes a big difference in texture and flavor.',
   content4:'One secret many home cooks overlook is saving some of the pasta water. Italian chefs use this starchy water to blend with sauces, helping them stick to the pasta. For instance, when tossing spaghetti with carbonara or cacio e pepe, adding a splash of pasta water creates a creamy, velvety sauce without the need for heavy cream. It’s a small trick, but it’s what gives authentic pasta dishes their signature texture.',
   content5:'Equally important is combining the pasta with the sauce properly. In Italy, chefs never simply dump sauce over pasta on a plate. Instead, they finish cooking the pasta in the pan with the sauce for a minute or two, allowing the pasta to absorb flavors. This technique makes the dish cohesive, as the pasta and sauce become one, rather than tasting like two separate elements..',
   content6:'Finally, Italian chefs emphasize simplicity and quality of ingredients. A perfect pasta dish doesn’t require dozens of spices or complex steps. High-quality olive oil, fresh garlic, ripe tomatoes, and a touch of fresh herbs can elevate a dish more than heavy seasonings or additives. Italians believe in letting the natural flavors of each ingredient shine through, making the pasta the true star of the dish.',
   content7:'Mastering pasta the Italian way is about respecting tradition, paying attention to technique, and using the best ingredients you can find. From choosing the right pasta shape to finishing it in the sauce, these timeless tips from Italian chefs can help anyone turn an everyday meal into an authentic, flavorful experience. Once you embrace these methods, cooking pasta will feel less like following a recipe and more like practicing an art form.',
    read_time: 6,
    slug: 'perfect-pasta-tips'
  },
  {
    id: 'blog4',
    title: 'Seasonal Cooking: Making the Most of Fresh Ingredients',
    excerpt: 'Explore the benefits of cooking with seasonal produce and learn how to create flavorful dishes using ingredients at their peak.',
    image_url: 'https://images.pexels.com/photos/1435903/pexels-photo-1435903.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Emma Thompson',
    date: '2024-02-28',
    content:'Seasonal cooking is more than a culinary trend—it’s a lifestyle that connects us to nature’s rhythm and helps us make the most of the freshest, most flavorful ingredients available throughout the year. By aligning your meals with what’s naturally in season, you not only enjoy better taste and nutrition but also support local farmers and reduce your carbon footprint. Italian chefs and home cooks worldwide agree: seasonal food is the cornerstone of great cooking.',
   content1:'The biggest advantage of seasonal cooking is freshness and flavor. Ingredients harvested at their peak ripeness have a depth of flavor that simply can’t be matched by out-of-season produce. For example, a tomato picked in the height of summer is juicy, sweet, and full of natural flavor—completely different from one grown in winter in a greenhouse. Using seasonal produce ensures that your meals taste vibrant and naturally delicious without needing excessive seasoning.',
   content2:'Seasonal cooking is also about nutrition at its best. Fruits and vegetables harvested at the right time retain more vitamins, minerals, and antioxidants compared to those stored for months. Eating seasonally means your body gets exactly what it needs throughout the year. For instance, citrus fruits like oranges and grapefruits are abundant in winter when your immune system most needs vitamin C. Similarly, leafy greens in spring provide a natural detox after heavier winter meals.',
   content3:'Another benefit is cost-effectiveness. Buying produce in season is often cheaper because it’s more plentiful and doesn’t require costly storage or transportation. Visiting local farmers’ markets is a great way to discover what’s fresh while also supporting your community. Many chefs even build their menus entirely around seasonal availability, letting the harvest dictate the dishes they prepare.',
   content4:'Seasonal cooking also encourages creativity in the kitchen. Each season brings its own set of ingredients, challenging you to experiment with new recipes and flavors. In summer, you might prepare light salads, chilled soups, or grilled vegetables. In autumn, root vegetables, squashes, and apples inspire hearty soups, stews, and baked dishes. Winter calls for comfort foods with cabbages, citrus, and legumes, while spring invites fresh herbs, asparagus, and tender greens.',
   content5:'One important principle Italian chefs emphasize is to let seasonal ingredients shine. Instead of masking their flavors with heavy sauces or excessive spices, cook them simply—like roasting vegetables with olive oil, grilling fresh fish with herbs, or tossing pasta with seasonal greens and garlic. The goal is to highlight the ingredient’s natural taste and freshness.',
   content6:'Ultimately, seasonal cooking is about connection—connection to the land, to your community, and to your body’s needs. By paying attention to what’s naturally available during each season, you’ll not only improve your cooking but also enjoy a more sustainable and mindful lifestyle. Whether you’re a home cook or an aspiring chef, embracing seasonal ingredients will help you discover new flavors, improve your health, and deepen your appreciation for the food on your plate.',
   content7:'Finally, no kitchen is complete without a wooden spoon and a spatula. These basic tools are surprisingly versatile and durable. Wooden spoons don’t scratch cookware and are heat resistant, while spatulas are perfect for scraping every bit of sauce or flipping food evenly. They may be small, but they play a big role in ensuring your meals turn out just right.',
    read_time: 7,
    slug: 'seasonal-cooking'
  },
  {
    id: 'blog5',
    title: 'Baking Science: Understanding How Ingredients Work',
    excerpt: 'Dive into the fascinating world of baking science and learn why certain ingredients react the way they do in your favorite recipes.',
    image_url: 'https://images.pexels.com/photos/3776942/pexels-photo-3776942.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'David Park',
    date: '2024-02-20',
    read_time: 10,
    content:'Baking may seem like an art, but at its core, it’s a precise science where each ingredient plays a unique role. Unlike cooking, where improvisation often works, baking requires accuracy and balance. The right mix of flour, sugar, eggs, butter, and leavening agents determines whether you end up with a fluffy cake, chewy cookies, or a dense loaf of bread. Understanding how these ingredients interact helps bakers troubleshoot problems and create consistently delicious results.',
   content1:'At the heart of most baked goods is flour, which provides structure. When mixed with water, flour forms gluten—a network of proteins that trap air and give baked goods their texture. Strong flours with high protein content, like bread flour, create chewy and elastic doughs, while low-protein flours, like cake flour, make tender and delicate desserts. Choosing the right flour is critical depending on whether you’re baking bread, cookies, or pastries.',
   content2:'Another crucial component is sugar, which does more than sweeten. Sugar affects texture, moisture, and even color. It tenderizes dough by interfering with gluten formation, helping cookies stay soft or cakes remain moist. During baking, sugar also caramelizes and contributes to the golden-brown crust we all love. In some recipes, sugar helps with aeration, as in creaming butter and sugar together to trap air for a lighter cake.',
   content3:'Fats like butter, oil, or shortening play a dual role in flavor and texture. Butter adds richness and creates flakiness in pastries, while oil keeps cakes moist for longer. Fats also coat flour particles, limiting gluten formation, which is why cookies and cakes are tender instead of tough. Beyond this, fats carry flavors, giving baked goods their indulgent mouthfeel. The choice of fat can dramatically change the outcome of a recipe.',
   content4:'Eggs act as binders and leavening agents. The proteins in egg whites add structure when beaten, while yolks contribute fat, richness, and emulsification, keeping ingredients like oil and water from separating. In recipes like meringues or sponge cakes, beaten egg whites provide volume and lightness. In custards or breads, eggs give color, elasticity, and shine. Without eggs, many baked goods would crumble or lack proper structure.',
   content5:'Equally important are leavening agents, such as baking powder, baking soda, and yeast. These ingredients produce gas (usually carbon dioxide) that gets trapped in the dough or batter, making it rise. Baking soda requires an acid to react, while baking powder contains both acid and base, making it more versatile. Yeast, on the other hand, relies on fermentation, creating complex flavors in breads and pastries while providing rise.',
   content6:'Finally, liquids and salt often go unnoticed but are essential. Water or milk hydrates flour, activates gluten, and dissolves sugar and salt. Salt balances sweetness, strengthens gluten, and enhances flavor. Without it, bread tastes flat, and cookies may seem overly sweet. Each ingredient—whether large or small—plays a critical role in the chemistry of baking.',
   content7:'Understanding the science behind baking transforms it from guesswork into mastery. When you know why your cookies spread too much or why your bread didn’t rise, you can adjust ingredients with confidence. Baking isn’t just about following recipes—it’s about chemistry, precision, and balance. By learning how ingredients work together, home bakers can elevate their skills and consistently create bakery-quality results at home.',

    slug: 'baking-science'
  },
  {
    id: 'blog6',
    title: 'Spice Up Your Life: A Guide to Global Spices',
    excerpt: 'Discover spices from around the world and learn how to use them to add depth and complexity to your everyday cooking.',
    image_url: 'https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Priya Sharma',
    date: '2024-02-15',
    read_time: 6,
content:'Spices have been at the heart of cooking for centuries, shaping cuisines, preserving food, and even fueling trade routes across the world. From the fiery chilies of Mexico to the fragrant cardamom of India, each spice tells a story of culture, tradition, and flavor. Understanding global spices is not just about adding heat or aroma to your dishes—it’s about appreciating the diversity of culinary traditions and learning how to balance and blend flavors.',
   content1:'One of the most widely used spice families is chili peppers, essential in cuisines from Mexico to Thailand. They bring heat and depth to dishes, with varieties ranging from smoky chipotle to fiery bird’s eye chilies. The level of heat is measured by the Scoville scale, and knowing how much spice to use is key. In Mexican salsas, Indian curries, or Korean kimchi, chilies provide not just heat but a complexity that defines the dish.',
   content2:'Another global favorite is cumin, prized for its earthy, nutty flavor. Found in Indian, Middle Eastern, and North African cooking, cumin seeds are often dry-roasted to release their oils before being ground. It’s an essential ingredient in garam masala, chili powders, and Moroccan tagines. Whether in a hearty curry or a simple stew, cumin adds depth and warmth that elevates the overall flavor profile.',
   content3:'Turmeric is another spice with global recognition, especially for its vibrant color and health benefits. Known as the “golden spice,” turmeric is a staple in Indian cooking and Southeast Asian curries. Beyond its culinary uses, it’s valued for its anti-inflammatory properties. Adding a pinch of turmeric not only enhances flavor but also gives dishes like rice, soups, and teas a rich golden hue.',
   content4:'From the Middle East to Scandinavia, cardamom is cherished for its sweet, floral notes. In Indian chai, cardamom pairs beautifully with cinnamon and cloves, while in Nordic countries, it flavors breads and pastries. Its versatility allows it to shine in both sweet and savory dishes, whether in a spiced curry or a creamy dessert. Cardamom demonstrates how a single spice can transcend borders and adapt to different cuisines.',
   content5:'Cinnamon and cloves are warming spices with global appeal. In Middle Eastern and Mediterranean cooking, cinnamon is used in savory stews, while in Western baking it flavors everything from cakes to holiday drinks. Cloves, with their strong aroma, are often used sparingly but play a crucial role in spice blends like Chinese five-spice and garam masala. Together, they create depth and comfort in dishes across cultures.',
   content6:'Finally, herbs and spice blends highlight the creativity of global cooking. Za’atar from the Middle East, ras el hanout from Morocco, curry powders from India, and Cajun seasoning from Louisiana all showcase how spices are combined to create signature flavors. Exploring these blends introduces you to entirely new taste experiences and helps you understand how cultures use spices to define their culinary identity.',
   content7:'Spices are the passport to global cooking, offering flavors that can transport you across continents in a single bite. By experimenting with spices from different regions, you can expand your cooking skills and bring authenticity to your dishes. From the heat of chilies to the sweetness of cinnamon, every spice has a role to play. Mastering them is not just about cooking—it’s about connecting with the world through flavor.',

    slug: 'guide-to-spices'
  }
];
